import { StructuredData } from './types';

export const MOCK_DATA: StructuredData = {
  news: [
    {
      platform: 'news',
      source: 'The Times of India',
      headline: 'BJP announces major infrastructure push in Uttar Pradesh',
      text: 'BJP announces major infrastructure push in Uttar Pradesh, focusing on rural connectivity and digital literacy programs across 50 districts.',
      url: 'https://timesofindia.indiatimes.com',
      time: '2026-02-19T06:30:00Z',
      language: 'en',
      engagement: { likes: 1200, shares: 450, comments: 89 },
      sentiment: { sentiment: 'POSITIVE', confidence: 0.9, intensity: 'HIGH', reason: 'Focus on development and infrastructure is well-received.' },
      weightedScore: 85,
      state: 'Uttar Pradesh',
    },
    {
      platform: 'news',
      source: 'Hindustan Times',
      headline: 'PM Modi inaugurates 5000 km of new highways across India',
      text: 'Prime Minister Narendra Modi inaugurated over 5000 km of new highway projects in a virtual ceremony attended by Chief Ministers of 12 states.',
      url: 'https://hindustantimes.com',
      time: '2026-02-19T07:00:00Z',
      language: 'en',
      engagement: { likes: 3200, shares: 1100, comments: 240 },
      sentiment: { sentiment: 'POSITIVE', confidence: 0.93, intensity: 'HIGH', reason: 'Large-scale infrastructure positive for public image.' },
      weightedScore: 91,
    },
    {
      platform: 'news',
      source: 'Maharashtra Times',
      headline: 'New industrial policy in Maharashtra expected to create 5 lakh jobs',
      text: 'The new industrial policy in Maharashtra is expected to generate approximately 5 lakh employment opportunities over the next two years.',
      url: 'https://maharashtratimes.com',
      time: '2026-02-19T07:45:00Z',
      language: 'hi',
      engagement: { likes: 2500, shares: 900, comments: 200 },
      sentiment: { sentiment: 'POSITIVE', confidence: 0.92, intensity: 'HIGH', reason: 'Job creation is a top priority for voters.' },
      weightedScore: 88,
      state: 'Maharashtra',
    },
    {
      platform: 'news',
      source: 'Dainik Jagran',
      headline: 'Opposition parties criticize new tax reforms burden on middle class',
      text: 'Opposition parties have come out strongly against the new tax reform bill, claiming it unfairly burdens the salaried middle class while giving relief to corporates.',
      url: 'https://jagran.com',
      time: '2026-02-19T08:15:00Z',
      language: 'hi',
      engagement: { likes: 800, shares: 300, comments: 150 },
      sentiment: { sentiment: 'NEGATIVE', confidence: 0.85, intensity: 'MEDIUM', reason: 'Economic concerns raised by opposition gaining traction.' },
      weightedScore: 40,
    },
    {
      platform: 'news',
      source: 'NDTV',
      headline: 'Farmers protest outside state assembly over crop insurance delays',
      text: 'Thousands of farmers staged a protest outside the state assembly demanding timely release of pending crop insurance claims worth ₹800 crore.',
      url: 'https://ndtv.com',
      time: '2026-02-19T10:00:00Z',
      language: 'en',
      engagement: { likes: 5000, shares: 2100, comments: 870 },
      sentiment: { sentiment: 'NEGATIVE', confidence: 0.88, intensity: 'HIGH', reason: 'Farmer grievances on insurance delays gaining media focus.' },
      weightedScore: 28,
      state: 'Madhya Pradesh',
    },
    {
      platform: 'news',
      source: 'The Hindu',
      headline: 'Centre reviews progress on Smart Cities Mission ahead of deadline',
      text: 'The central government reviewed the progress of the Smart Cities Mission with state officials ahead of the project completion deadline in March.',
      url: 'https://thehindu.com',
      time: '2026-02-19T09:00:00Z',
      language: 'en',
      engagement: { likes: 600, shares: 180, comments: 45 },
      sentiment: { sentiment: 'NEUTRAL', confidence: 0.78, intensity: 'LOW', reason: 'Administrative review with no clear public verdict.' },
      weightedScore: 55,
    },
  ],
  x: [
    {
      platform: 'x',
      source: '@BJP4India',
      headline: 'India reaches new milestone in renewable energy production',
      text: 'Under the leadership of PM @narendramodi, India reaches a new milestone in renewable energy production. 100GW solar achieved! #NewIndia #GreenIndia',
      url: 'https://x.com/BJP4India/status/1234567890',
      time: '2026-02-19T05:30:00Z',
      language: 'en',
      engagement: { likes: 15000, shares: 5000, comments: 400 },
      sentiment: { sentiment: 'POSITIVE', confidence: 0.95, intensity: 'HIGH', reason: 'High engagement on achievement-oriented posts.' },
      weightedScore: 95,
    },
    {
      platform: 'x',
      source: '@BJP4Maharashtra',
      headline: 'Massive support seen at Vikas Yatra in Pune',
      text: 'Massive support for the Vikas Yatra in Pune today! People of Maharashtra trust the double-engine government. #BJPMaharashtra',
      url: 'https://x.com/BJP4Maharashtra/status/1234567891',
      time: '2026-02-19T11:00:00Z',
      language: 'en',
      engagement: { likes: 8000, shares: 2500, comments: 600 },
      sentiment: { sentiment: 'POSITIVE', confidence: 0.93, intensity: 'HIGH', reason: 'Strong ground presence in key urban centers.' },
      weightedScore: 92,
      state: 'Maharashtra',
    },
    {
      platform: 'x',
      source: '@OppositionLeader',
      headline: 'Administration blamed for rising urban unemployment rates',
      text: 'The current administration has failed to address the rising unemployment rates in urban sectors. Promises were made, but where are the jobs? #Jobs #Economy',
      url: 'https://x.com/OppositionLeader/status/1234567892',
      time: '2026-02-19T09:30:00Z',
      language: 'en',
      engagement: { likes: 5000, shares: 2000, comments: 1200 },
      sentiment: { sentiment: 'NEGATIVE', confidence: 0.8, intensity: 'MEDIUM', reason: 'Direct attack on governance performance gaining traction.' },
      weightedScore: 30,
    },
    {
      platform: 'x',
      source: '@PIBIndia',
      headline: 'Cabinet approves national water grid project worth ₹2 lakh crore',
      text: 'Cabinet approves national water grid project worth ₹2 lakh crore to connect 16 major rivers. This will benefit 300M Indians. #JalJeevanMission',
      url: 'https://x.com/PIBIndia/status/1234567893',
      time: '2026-02-19T12:00:00Z',
      language: 'en',
      engagement: { likes: 12000, shares: 4500, comments: 890 },
      sentiment: { sentiment: 'POSITIVE', confidence: 0.91, intensity: 'HIGH', reason: 'Water infrastructure plan has wide public appeal.' },
      weightedScore: 89,
    },
  ],
  instagram: [
    {
      platform: 'instagram',
      source: 'bjp4india',
      headline: 'Glimpses from the massive rally in Karnataka',
      text: 'Glimpses from the massive rally in Karnataka. The energy is infectious! The ground support has never been stronger. #BJPRally #Karnataka',
      url: 'https://instagram.com/p/123456',
      time: '2026-02-19T14:00:00Z',
      language: 'mixed',
      engagement: { likes: 45000, shares: 1200, comments: 800 },
      sentiment: { sentiment: 'POSITIVE', confidence: 0.9, intensity: 'HIGH', reason: 'Visual content showing strong ground support.' },
      weightedScore: 90,
      state: 'Karnataka',
    },
    {
      platform: 'instagram',
      source: 'narendramodi',
      headline: 'PM Modi flags off new Vande Bharat Express trains',
      text: 'Flagging off 10 new Vande Bharat Express trains today. Faster connectivity for a stronger India! #VandeBharat #RailwaysDevelopment',
      url: 'https://instagram.com/p/123457',
      time: '2026-02-19T10:30:00Z',
      language: 'en',
      engagement: { likes: 280000, shares: 12000, comments: 15000 },
      sentiment: { sentiment: 'POSITIVE', confidence: 0.97, intensity: 'HIGH', reason: 'PM Modi posts consistently have highest reach.' },
      weightedScore: 97,
    },
  ],
  facebook: [
    {
      platform: 'facebook',
      source: 'BJP Official',
      headline: 'New health scheme launched for senior citizens',
      text: 'Government launches new health scheme for senior citizens, providing free annual checkups and medicines worth ₹5000 per year.',
      url: 'https://facebook.com/BJP4India/posts/123456',
      time: '2026-02-19T08:00:00Z',
      language: 'hi',
      engagement: { likes: 25000, shares: 8000, comments: 1500 },
      sentiment: { sentiment: 'POSITIVE', confidence: 0.92, intensity: 'HIGH', reason: 'Welfare schemes consistently generate positive sentiment.' },
      weightedScore: 88,
    },
    {
      platform: 'facebook',
      source: 'Voice of Farmer',
      headline: 'Farmers demand better MSP and loan waivers',
      text: 'Farmer groups across 8 states are demanding revision of MSP rates and pending loan waiver implementation. They warn of intensifying protests.',
      url: 'https://facebook.com/FarmerVoice/posts/123457',
      time: '2026-02-19T11:30:00Z',
      language: 'hi',
      engagement: { likes: 18000, shares: 9000, comments: 2200 },
      sentiment: { sentiment: 'NEGATIVE', confidence: 0.87, intensity: 'HIGH', reason: 'Farmer distress remains key political vulnerability.' },
      weightedScore: 25,
      state: 'Punjab',
    },
  ],
};
